### ISSUE TITLE
xpblock bug 1.12.2

### ISSUE THREAD

**Issue by PyroXs** [bl4ckscor3/GlobalXP#20]
Hello, 
I installed some mods ( about 40 ), one of them is globalxp.
I have an issue with this mod: When i spend xp in the crafting table, and then i right click into the xpblock, i regain my xp.
Per example: I have 30 lvls, i enchant a sword and i then have 17 lvls, then i put my remaining xp into the block, and when i do this, the block tells me i have 30 lvls, i extract them and i have 30 lvls.
So i have infinite xp.
I would like to know how to solve this bug.
My installed mods are: 
Apple skin
Astral sorcery
BarrelsDrumsStorage and more
Baubles
Bettercaves
Better PvP mod
BrutalZombieSiege
CarryOn
Chargers
Chisel-MC
CraftTweaker 2
CreativeCore
CTM-MC
Cucumber
Decocraft
enchcontrol
extrautils2
FastLeafDecay
fence jumper
Forgelin
globalxp 1.12.x - v1.4
Hwyla
industrialforegoing
inventorystorer
ironchest
ironfurnaces
IronJetpacks
itemscroller
Jei
journeymap
JustEnoughCalculation
JustEnoughResources
Kleeslabs
moreoverlays
Morpheus
multimob
OnlinePictureFrame
Optifine
OresAboveDiamonds
PTRlib
realfillingcabinet
RoguelikeDungeons
simplehammers
simpleharvest
simplestoragenetwork
Simply Platinum mod
SolarFluxReborn
speedyladders
tesla core lib
travellersboots
unenchanting

Thanks for your help!

**Comment by bl4ckscor3** [comment]
1. You are using an outdated version of the mod. Don't report issues with a software if you are not using its latest version because the issue you are reporting might already be fixed in later versions. Always confirm that your issue still occurs in the latest version, then report it using a descriptive title (The title you chose for this issue is not descriptive. Something like "XP Block duplicating experience" would have been good). Get the most recent version of Global XP for Minecraft 1.12.2 here: https://www.curseforge.com/minecraft/mc-mods/global-xp/files/2818519
2. I am no longer developing my mods for Minecraft 1.12.2. This means that I will not fix any bugs and will not add any new features to the Minecraft 1.12.2 editions of my mods.
