### ISSUE TITLE
Graphical Glitches

### ISSUE THREAD

**Issue by Coraline77447** [bl4ckscor3/GlobalXP#22]
Hi! I'm experiencing some graphical glitches while using this mod. It first started happening when I placed the Global XP block down in my attic in my house on my world called Coraline World 1.16.3 (Modded) (which was unfortunately been deleted cause some experimental settings that another mod was using broke which made the world unjoinable/unplayable) that I can see my chests and bed through blocks when I looked down and I can see chests that are underground and now the issue has gotten worse that in certain directions that I looked when near the Global XP block (like 10 or so blocks away) the chests and bed have graphical glitches and when I slept in my bed my chest area of my character would blend in with the bed. Also now I'm able to see other stuff through blocks like banners and when I looked at my Blight Wolves (Blights are from Scaling Health mod btw) I can see other mobs/entities through blocks which will appear in a pail/bright red or blue color. P.s. I would normally just ignore graphical glitches but since the problem is getting worse and I can't simply ignore them anymore so that's why I reported this issue now instead of waiting for someone else to report this issue. Btw hope this ain't too much to read!..

**Comment by bl4ckscor3** [comment]
I released a tentative fix for this. If the new version doesn't resolve the issue for you, then I'm not sure if the issue is even Global XP. You may have another faulty mod in your installation. If you have OptiFine installed, try deinstalling that one as well.

And please _always_ report issues. Don't wait for someone else to report them. The earlier an issue can be fixed, the better.
