### ISSUE TITLE
[1.15.2] Storage resetting on each load

### ISSUE THREAD

**Issue by Janitor53** [bl4ckscor3/GlobalXP#26]
Forge: forge-1.15.2-31.2.47-universal.jar
Mod: globalxp-1.15.2-v1.6.jar
Java: 1.8.0_252 OpenJDK 64-Bit Server VM GraalVM CE 20.1.0
No other mods are installed. 
Steps to reproduce: Store some xp in block, exit to menu and load again. Storage is empty. There is an error in log:
https://pastebin.com/y5dwVY3E

**Comment by bl4ckscor3** [comment]
Thanks for reporting!

**Comment by Coraline77447** [comment]
Even tho this is for a different version of Global XP but I'm experiencing an issue similar to this that the stored XP in the Global XP block resets to 0. 
On my world called Coraline World 2 1.16.5 (Modded) when I came back from the Nether that my XP in the Global XP block didn't have the XP that was stored in it before I went to the Nether and when I came back on the world before I went to the Nether the Global XP block didn't have the XP that I stored in it before the latest update. 
Even though I should go open a bug report on here about this but why not just tell what I've experienced with the latest update of the mod as of the issue I've encountered in the replies of this closed issue? 
Btw I'll not be playing with this mod till this issue is fixed in 1.16.X and on my previous modded world and my new one that I'm about to create I have a mod that adds more gamerules that allows me to keep my experience on death called keepInventoryexperince. 
Also I think that Coral Tombstone mod may prevent my XP from being lost on death. So both of these mods are prefect alternatives to Global XP for XP storage and to keep my XP on death.

**Comment by bl4ckscor3** [comment]
@Coraline77447 update Global XP to at least v1.6.1 to fix this issue. This version was released yesterday.

**Comment by Coraline77447** [comment]
Sorry to not include what version of Mc that I'd encountered the bug on which was 1.16.5 not 1.15.2, hints the name of the modded world(s) I make and play on that I said above. Also I've gotten the latest release but don't know if 1.7 would fix that issue tho..
But my next world that I'm gonna make I'll only allow 50/55 mods maximum, no more than 55 so that the world would be lightweight so that I can have a little bit more framerate than my previous worlds that had more mods since my RAM size for both virtual and physical RAM are limited on my current laptop :<
What I'm sayin is that I'm still not gonna play with Global XP so that I can get some more framerate.

**Comment by bl4ckscor3** [comment]
The issue is fixed in v1.7 because the issue was fixed in v1.6.1. And since there is a v1.6.1 for Minecraft 1.16.5 as well, the issue was fixed there, too.

**Comment by Coraline77447** [comment]
Wait, so that issue was in 1.6 which I had plans to revert back to the previous version prier to 1.6. (1.5)
but I didn't know that you've released a hot fix update yesterday cause I decided to stop playin with Global XP yesterday cause of the two mods that I have that prevents my XP from being lost on death and that the bug was preventing me from storing XP into the Global XP block. Thanks for the info btw.
