### ISSUE TITLE
Global XP Crashes Minecraft v1.20.1 when updating to 10.4

### ISSUE THREAD

**Issue by SirTwsted** [bl4ckscor3/GlobalXP#38]
When updating the mod from 10.3  to  10.4  
the mod crashes Minecraft.  It only gives Error Code (Exit -1) with no logs for some odd reason.
I tested it several times by completely disabling the Global XP mod and reactivating the mod.

And every time I reactivate v10.4 it crashes Minecraft.
But,  When I revert back to 10.3 , Minecraft then properly works again.

Minecraft v1.20.1
Forge v47.1.46
Global XP v10.4

🤷‍♀️

**Comment by Zedrimar** [comment]
Thankfully AT launcher's console showed output, because the log file didn't have crap. Thankfully it was just because of a misplaced period in the file name.

Should be: "globalxp-forge-1.20-1.10.4" rather than "globalxp-forge-.1.20-1.10.4". Minecraft apparently doesn't like there not being a number before the period. 

Simply renaming the file to remove the extra period after the second dash will let it load fine.

**Comment by bl4ckscor3** [comment]
Sorry about that, and thank you very much for looking into this and reporting it! I reuploaded the file with a fixed name. Since only a language file was added between the updates, I didn't think of testing the jar file before uploading it. I'll be more vigilant in the future.

**Comment by Zedrimar** [comment]
No worries, it happens. Thank you for making such an amazing mod!
